# Generated by Django 3.2.8 on 2024-02-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duinisveldbreugem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_type',
        ),
    ]
