# Generated by Django 3.2.8 on 2024-02-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duinisveldbreugem', '0002_remove_invoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='duinisveldbreugem.invoice'),
            preserve_default=False,
        ),
    ]
