# Generated by Django 3.2.8 on 2021-10-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='article',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
