# Generated by Django 3.2.8 on 2021-10-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0005_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='action_log',
            name='post_to_database',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='action_log',
            name='test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='action_log',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
