# Generated by Django 3.2.8 on 2021-10-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0006_auto_20211025_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error_log',
            old_name='description',
            new_name='error',
        ),
        migrations.RemoveField(
            model_name='error_log',
            name='file_name',
        ),
        migrations.AddField(
            model_name='error_log',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hbm_app.action_log'),
            preserve_default=False,
        ),
    ]
