# Generated by Django 3.2.8 on 2021-10-29 10:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0007_auto_20211025_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hbm_app.customer')),
            ],
        ),
    ]
