# Generated by Django 3.2.8 on 2021-10-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0008_auto_20211029_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='interval',
            field=models.IntegerField(choices=[('daily', '1')]),
        ),
    ]
