# Generated by Django 3.2.8 on 2021-10-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0009_alter_customer_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='interval',
            field=models.IntegerField(choices=[('1', 'daily')]),
        ),
    ]
