# Generated by Django 3.2.8 on 2021-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0010_alter_customer_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='interval',
            field=models.IntegerField(default=1),
        ),
    ]
