# Generated by Django 3.2.8 on 2021-12-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0011_alter_customer_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='interval',
            field=models.IntegerField(default=1, help_text='Note: Enter number of days here.'),
        ),
        migrations.CreateModel(
            name='AhTransactionsDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('type_transaction', models.CharField(help_text='Defines whether the transaction is a regular or action.', max_length=200)),
                ('estimation_units', models.IntegerField(blank=True, help_text='Prognose', null=True)),
                ('sold_units', models.FloatField(blank=True, help_text='Realisatie', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hbm_app.customer')),
            ],
        ),
    ]
