# Generated by Django 3.2.8 on 2021-12-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0012_auto_20211201_2110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AhTransactionsDay',
            new_name='AhDayTransactions',
        ),
    ]
