# Generated by Django 3.2.8 on 2021-12-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0013_rename_ahtransactionsday_ahdaytransactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AhDayTransactions',
            new_name='AhDayTransaction',
        ),
    ]
