# Generated by Django 3.2.8 on 2021-12-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0014_rename_ahdaytransactions_ahdaytransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahdaytransaction',
            name='customer',
        ),
    ]
