# Generated by Django 3.2.8 on 2021-12-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0015_remove_ahdaytransaction_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahdaytransaction',
            name='sold_units',
            field=models.IntegerField(blank=True, help_text='Realisatie', null=True),
        ),
    ]
