# Generated by Django 3.2.8 on 2021-12-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0017_auto_20211202_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action_Log',
            new_name='ActionLog',
        ),
        migrations.RenameModel(
            old_name='Error_Log',
            new_name='ErrorLog',
        ),
    ]
