# Generated by Django 3.2.8 on 2021-12-02 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0018_auto_20211202_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahdaytransaction',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='hbm_app.customer'),
            preserve_default=False,
        ),
    ]
