# Generated by Django 3.2.8 on 2021-12-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0019_ahdaytransaction_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhWeekTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('year', models.IntegerField(help_text='Jaar')),
                ('article_number', models.IntegerField(help_text='Nasa#')),
                ('transaction_type', models.CharField(help_text='Actie', max_length=200)),
                ('forcast_number_of_units', models.IntegerField(blank=True, help_text='Prognose - Aantal CE', null=True)),
                ('forcast_purchase_price', models.FloatField(blank=True, help_text='Prognose - Inkoopprijs', null=True)),
                ('forcast_sale_price', models.FloatField(blank=True, help_text='Prognose - Verkoopprijs', null=True)),
                ('forcast_revenue', models.IntegerField(blank=True, help_text='Prognose - Ozmet', null=True)),
                ('actual_number_of_units', models.IntegerField(blank=True, help_text='Realisatie - Aantal CE', null=True)),
                ('actual_revenue', models.IntegerField(blank=True, help_text='Realisatie - Ozmet', null=True)),
                ('actual_gross_profit', models.IntegerField(blank=True, help_text='Realisatie - Brutowinst', null=True)),
                ('actual_loss', models.IntegerField(blank=True, help_text='Realisatie - Afboekingen', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='column_gross_profit',
            field=models.CharField(blank=True, help_text='Describe column name for the gross profit column, if any.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='column_loss',
            field=models.CharField(blank=True, help_text='Describe column name for the loss column, if any.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='column_number_of_units',
            field=models.CharField(blank=True, help_text='Describe column name for the number of units column, if any.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='column_purchase_price',
            field=models.CharField(blank=True, help_text='Describe column name for the purchase price column, if any.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='column_revenue',
            field=models.CharField(blank=True, help_text='Describe column name for the revenue column, if any.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='column_sale_price',
            field=models.CharField(blank=True, help_text='Describe column name for the sale price column, if any.', max_length=200, null=True),
        ),
    ]
