# Generated by Django 3.2.8 on 2021-12-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0020_auto_20211206_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='column_gross_profit',
            field=models.CharField(blank=True, help_text='AH: Describe column name for the gross profit column, if any.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='column_loss',
            field=models.CharField(blank=True, help_text='AH: Describe column name for the loss column, if any.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='column_number_of_units',
            field=models.CharField(blank=True, help_text='AH: Describe column name for the number of units column, if any.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='column_purchase_price',
            field=models.CharField(blank=True, help_text='AH: Describe column name for the purchase price column, if any.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='column_revenue',
            field=models.CharField(blank=True, help_text='AH: Describe column name for the revenue column, if any.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='column_sale_price',
            field=models.CharField(blank=True, help_text='AH: Describe column name for the sale price column, if any.', max_length=200, null=True),
        ),
    ]
