# Generated by Django 3.2.8 on 2021-12-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0021_auto_20211206_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cell_actual_forcast_number_of_units',
            field=models.IntegerField(blank=True, help_text='AH: Enter cell coordinate (e.g. A1) for number of unit column in Actual, if any', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cell_actual_forcast_revenue',
            field=models.IntegerField(blank=True, help_text='AH: Enter cell coordinate (e.g. A1) for the revenue column in the Actual, if any', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cell_forcast_number_of_units',
            field=models.IntegerField(blank=True, help_text='AH: Enter cell coordinate (e.g. A1) for number of unit column in the forcast, if any', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cell_forcast_revenue',
            field=models.IntegerField(blank=True, help_text='AH: Enter cell coordinate (e.g. A1) for the revenue column in the forcast, if any', null=True),
        ),
    ]
