# Generated by Django 3.2.8 on 2021-12-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0023_auto_20211206_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahweektransaction',
            old_name='forcast_number_of_units',
            new_name='forecast_number_of_units',
        ),
        migrations.RenameField(
            model_name='ahweektransaction',
            old_name='forcast_purchase_price',
            new_name='forecast_purchase_price',
        ),
        migrations.RenameField(
            model_name='ahweektransaction',
            old_name='forcast_revenue',
            new_name='forecast_revenue',
        ),
        migrations.RenameField(
            model_name='ahweektransaction',
            old_name='forcast_sale_price',
            new_name='forecast_sale_price',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cell_actual_forcast_number_of_units',
            new_name='cell_actual_forecast_number_of_units',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cell_actual_forcast_revenue',
            new_name='cell_actual_forecast_revenue',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cell_forcast_number_of_units',
            new_name='cell_forecast_number_of_units',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cell_forcast_revenue',
            new_name='cell_forecast_revenue',
        ),
    ]
