# Generated by Django 3.2.8 on 2021-12-07 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0025_auto_20211207_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahdaytransaction',
            name='customer',
        ),
    ]
