# Generated by Django 3.2.8 on 2021-12-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0026_remove_ahdaytransaction_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('receive_sync_successull_email', models.BooleanField(default=False)),
                ('receive_sync_unsuccessull_email', models.BooleanField(default=False)),
                ('receive_missing_schedule_email', models.BooleanField(default=False)),
            ],
        ),
    ]
