# Generated by Django 3.2.8 on 2021-12-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0027_receiveremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCommands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=200)),
            ],
        ),
    ]
