# Generated by Django 3.2.8 on 2022-01-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0029_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hbm_app.customer'),
        ),
    ]
