# Generated by Django 3.2.8 on 2022-02-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0029_rename_customcommands_customcommand'),
        ('hbm_app', '0030_article_customer'),
    ]

    operations = [
    ]
