# Generated by Django 3.2.8 on 2022-02-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0031_merge_20220126_1139'),
        ('hbm_app', '0032_article_article_type'),
    ]

    operations = [
    ]
