# Generated by Django 3.2.8 on 2022-06-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0032_article_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('Boeket', 'Boeket'), ('Mono', 'Mono'), ('Planten', 'Planten'), ('Arrangement', 'Arrangement'), ('Geen type', 'Geen type')], default='Geen type', max_length=20),
        ),
    ]
