# Generated by Django 3.2.8 on 2022-09-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0033_alter_article_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_number', models.IntegerField()),
                ('store_name', models.CharField(max_length=200)),
                ('gtin_number', models.IntegerField()),
                ('units', models.IntegerField()),
                ('turnover', models.FloatField()),
                ('start_date', models.DateField()),
                ('store_category', models.CharField(choices=[('Bloemen', 'Bloemen'), ('Planten', 'Planten')], max_length=50)),
            ],
        ),
    ]
