# Generated by Django 3.2.8 on 2022-06-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0033_alter_article_article_type'),
        ('hbm_app', '0033_merge_20220222_0937'),
    ]

    operations = [
    ]
