# Generated by Django 3.2.8 on 2022-09-07 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0034_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
