# Generated by Django 3.2.8 on 2022-09-13 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0035_store_end_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Agreflor',
        ),
    ]
