# Generated by Django 3.2.8 on 2022-09-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0036_rename_store_agreflor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreflor',
            old_name='store_category',
            new_name='product_category',
        ),
    ]
