# Generated by Django 3.2.8 on 2022-09-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0034_merge_20220607_1559'),
        ('hbm_app', '0037_rename_store_category_agreflor_product_category'),
    ]

    operations = [
    ]
