# Generated by Django 3.2.8 on 2022-12-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0037_rename_store_category_agreflor_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antenna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number_debtor', models.IntegerField()),
                ('debtor_number', models.IntegerField()),
                ('debtor_name', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('week', models.CharField(max_length=128)),
                ('invoice_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=128)),
                ('invoice_text', models.CharField(max_length=256)),
                ('invoice_quantity', models.TimeField()),
                ('invoice_minutes', models.FloatField()),
                ('invoice_type', models.CharField(max_length=128)),
                ('rate', models.FloatField()),
                ('type_hour', models.CharField(max_length=128)),
                ('allowace_rate', models.FloatField()),
                ('invoice_amount', models.FloatField()),
                ('vat', models.FloatField()),
                ('resource_number', models.IntegerField()),
                ('resource_name', models.CharField(max_length=128)),
                ('date_worked', models.DateField()),
            ],
        ),
    ]
