# Generated by Django 3.2.8 on 2023-01-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0039_alter_antenna_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenna',
            name='date_worked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antenna',
            name='invoice_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antenna',
            name='invoice_quantity',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antenna',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antenna',
            name='type_hour',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
