# Generated by Django 3.2.8 on 2023-01-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0038_merge_20220916_0856'),
        ('hbm_app', '0040_auto_20230116_1714'),
    ]

    operations = [
    ]
