# Generated by Django 3.2.8 on 2023-03-03 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0040_auto_20230116_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReceiverEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email_address', models.EmailField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('interval', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=128)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hbm_app.customer')),
            ],
            options={
                'unique_together': {('customer', 'email_address')},
            },
        ),
    ]
