# Generated by Django 3.2.8 on 2023-03-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0041_customerreceiveremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreceiveremail',
            name='last_sent_email_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
