# Generated by Django 3.2.8 on 2023-03-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0041_merge_20230131_1212'),
        ('hbm_app', '0042_customerreceiveremail_last_sent_email_time'),
    ]

    operations = [
    ]
