# Generated by Django 3.2.8 on 2023-04-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0042_customerreceiveremail_last_sent_email_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wematrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('date', models.DateField()),
                ('loading_address', models.CharField(max_length=512)),
                ('file', models.FloatField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=512)),
                ('unloading_address', models.CharField(max_length=512)),
                ('vat_code', models.CharField(max_length=64)),
                ('unit_price', models.FloatField()),
                ('amount', models.FloatField()),
                ('file_reference', models.CharField(blank=True, max_length=256, null=True)),
                ('invoice_number', models.BigIntegerField()),
            ],
        ),
    ]
