# Generated by Django 3.2.8 on 2023-04-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0043_merge_20230314_2110'),
        ('hbm_app', '0043_wematrans'),
    ]

    operations = [
    ]
