# Generated by Django 3.2.8 on 2023-10-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0043_wematrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhPeriodTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Datum')),
                ('week', models.IntegerField(help_text='Week')),
                ('year', models.IntegerField(help_text='Jaar')),
                ('day', models.IntegerField(help_text='Dag')),
                ('nasa_number', models.IntegerField(help_text='NasaNr')),
                ('type', models.CharField(max_length=200)),
                ('value', models.FloatField(blank=True, help_text='Waarde', null=True)),
            ],
        ),
    ]
