# Generated by Django 3.2.8 on 2023-10-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0044_ahperiodtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahperiodtransaction',
            old_name='type',
            new_name='type_transaction',
        ),
    ]
