# Generated by Django 3.2.8 on 2023-10-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0045_rename_type_ahperiodtransaction_type_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahperiodtransaction',
            name='day',
            field=models.CharField(help_text='Dag', max_length=20),
        ),
    ]
