# Generated by Django 3.2.8 on 2023-11-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0044_merge_0043_merge_20230314_2110_0043_wematrans'),
        ('hbm_app', '0047_alter_ahperiodtransaction_week'),
    ]

    operations = [
    ]
