# Generated by Django 3.2.8 on 2024-02-05 19:22

from django.db import migrations
from hbm_app.models import Article, ArticleType


def update_article_types_for_existing_articles(apps, schema_editor):

    #write your code here
    #get all the articles, get article_type, check if article_type exists in ArticleType model, if yes, get type and assign it as a foreign key
    all_articles = Article.objects.all()
    for article in all_articles:
        article_type, created = ArticleType.objects.get_or_create(name=article.article_type)
        article.art_type = article_type
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0049_auto_20240205_2014'),
    ]

    operations = [
        migrations.RunPython(update_article_types_for_existing_articles),
    ]
