# Generated by Django 3.2.8 on 2024-02-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0050_auto_20240205_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_type',
        ),
    ]
