# Generated by Django 3.2.8 on 2024-02-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0051_remove_article_article_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='art_type',
            new_name='article_type',
        ),
    ]
