# Generated by Django 3.2.8 on 2024-02-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0053_auto_20240205_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='column_rotation',
            field=models.CharField(blank=True, help_text='AH Week: Describe column name for the rotation column, if any.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='column_store_count',
            field=models.CharField(blank=True, help_text='AH Week: Describe column name for the store count column, if any.', max_length=200, null=True),
        ),
    ]
