# Generated by Django 3.2.8 on 2024-02-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0054_auto_20240212_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahweektransaction',
            name='rotations',
            field=models.IntegerField(blank=True, help_text='Rotatie', null=True),
        ),
        migrations.AddField(
            model_name='ahweektransaction',
            name='store_count',
            field=models.IntegerField(blank=True, help_text='Aantal Filialen', null=True),
        ),
    ]
