# Generated by Django 3.2.8 on 2024-02-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0055_auto_20240212_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahweektransaction',
            old_name='rotations',
            new_name='rotation',
        ),
    ]
