# Generated by Django 3.2.8 on 2024-02-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0056_rename_rotations_ahweektransaction_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahweektransaction',
            name='rotation',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Rotatie', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ahweektransaction',
            name='store_count',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Aantal Filialen', max_digits=10, null=True),
        ),
    ]
