# Generated by Django 3.2.8 on 2024-02-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0057_auto_20240212_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datedevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
