# Generated by Django 3.2.8 on 2024-02-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0058_alter_datedevent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='row_headers',
            field=models.IntegerField(blank=True, help_text='Enter row where the header is located.', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tab_name',
            field=models.CharField(blank=True, help_text='Note: Fill in name of the Excel sheet', max_length=200, null=True),
        ),
    ]
