# Generated by Django 3.2.8 on 2024-04-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbm_app', '0059_auto_20240226_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('read', models.BooleanField(default=True)),
                ('file_path', models.CharField(max_length=1024)),
                ('recieve_date', models.DateTimeField(blank=True, null=True)),
                ('process_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hbm_app.customer')),
            ],
        ),
    ]
