# Generated by Django 3.2.8 on 2024-03-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floriway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.FloatField()),
                ('date', models.DateField()),
                ('loading_address', models.CharField(max_length=512)),
                ('file', models.FloatField()),
                ('number', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=256, null=True)),
                ('unloading_address', models.CharField(max_length=512)),
                ('btw', models.FloatField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('file_reference', models.CharField(blank=True, max_length=256, null=True)),
                ('invoice_number', models.FloatField()),
            ],
        ),
    ]
